version: '3.8'

networks:
  dockerbridge:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:1111:2222:3333::/64

services:
  electric:
    image: '${ELECTRIC_IMAGE:-electricsql/electric:latest}'
    networks:
      - dockerbridge
    ports:
      - ${HTTP_PORT:-5133}:${HTTP_PORT:-5133}
      - ${PG_PROXY_PORT_PARSED:-65432}:${PG_PROXY_PORT_PARSED:-65432}
    environment:
      DATABASE_REQUIRE_SSL: ${DATABASE_REQUIRE_SSL:-}
      DATABASE_URL: ${DATABASE_URL:-}
      DATABASE_USE_IPV6: ${DATABASE_USE_IPV6:-}
      ELECTRIC_USE_IPV6: ${ELECTRIC_USE_IPV6:-}
      HTTP_PORT: ${HTTP_PORT:-5133}
      ELECTRIC_WRITE_TO_PG_MODE: ${ELECTRIC_WRITE_TO_PG_MODE:-}
      LOGICAL_PUBLISHER_HOST: ${LOGICAL_PUBLISHER_HOST:-}
      LOGICAL_PUBLISHER_PORT: ${LOGICAL_PUBLISHER_PORT:-5433}
      PG_PROXY_PASSWORD: ${PG_PROXY_PASSWORD:-proxy_password}
      PG_PROXY_PORT: ${PG_PROXY_PORT:-65432}
      AUTH_MODE: ${AUTH_MODE:-insecure}
      AUTH_JWT_ALG: ${AUTH_JWT_ALG:-}
      AUTH_JWT_AUD: ${AUTH_JWT_AUD:-}
      AUTH_JWT_ISS: ${AUTH_JWT_ISS:-}
      AUTH_JWT_KEY: ${AUTH_JWT_KEY:-}
      AUTH_JWT_NAMESPACE: ${AUTH_JWT_NAMESPACE:-}
